spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice_processor
    username: postgres
    password: postgres

logging:
  level:
    com.invoiceprocessor: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
