spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/invoice_processor
    username: postgres
    password: 

logging:
  level:
    com.invoiceprocessor: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
